import LinkedList from './linked lists.js';

const test = new LinkedList();
//console.log(test);
test.append('first');
//console.log(test);
test.append('second');
//console.log(test);
test.append('third');
//console.log(test);
test.prepend('fourth');
console.log(test);
console.log(`Size of list is ${test.getSize()}`);
console.log(`First element is ${test.getHead()}`);
console.log(`Last element is ${test.getTail()}`);
console.log(test.getNodeAt(1));
test.pop();
console.log(test);
console.log(test.contains('second'));
console.log(test.contains('third'));
console.log(test.find('first'));
console.log(test.find('third'));
